### ISSUE TITLE
syntax issues in pyReaver

### ISSUE THREAD

**Issue by thesle3p** [byt3bl33d3r/pyReaver#1]
Currently pyReaver does not run as it has multiple syntax errors in it one of which being present with the following:
python ./pyreaver.py 
  File "./pyreaver.py", line 43
    got_fist_half = False
    ^
IndentationError: unexpected indent

**Comment by byt3bl33d3r** [comment]
@thesle3p as the README.md says this is a work in progress and not even 1/4 finished
